### ISSUE TITLE
Remove githubfile's branch when PR is merged

### ISSUE THREAD

**Issue by barryib** [terraform-aws-modules/meta#10]
It would be nice to remove githubfile's branches after PRs are merged.

![image](https://user-images.githubusercontent.com/550783/77158648-089e6300-6aa4-11ea-9f5f-34208492265e.png)

**Comment by antonbabenko** [comment]
This has happened because first PR was merged successfully, and it changed the `master` branch. Then (during the next PR merge) the destination branch has not been updated automatically. Such updates failed and I used to rerun the same code once more.

`githubfile` provider does not have a way to rebase each PR before the merge.

In the meanwhile, I will run script to remove such branches from all repositories.

**Comment by antonbabenko** [comment]
This command removed remainings:
```
git branch -r | awk -F/ '/\/terraform-provider-githubfile-/{print $2}' | xargs -I {} git push origin --delete {}
```
