### ISSUE TITLE
Create Bot for closing old/stale issues

### ISSUE THREAD

**Issue by DrFaust92** [terraform-aws-modules/meta#13]
I'm assuming this is something that can be done with github action or similar
this is to declutter the noise and help focus on addressing actual issues

**Comment by antonbabenko** [comment]
Agree.

There is https://github.com/probot/stale which I was thinking we could use for this.

There is only one extra thing which I want to make sure it does - "close only issues where at least one comment has been posted". For example, if somebody asks a question we should not simply ignore it and close it after 30 days since posting.

In any case, please look into EKS module where this is already enabled and figure out `stale.yml` config which we can use for all repositories. We can test it on another active repo (eg, RDS or VPC).

**Comment by antonbabenko** [comment]
Thanks @DrFaust92 for your contribution.

As a summary, added stale.yml config into .github repo and enabled Stale bot for few more repositories to see how it works there.

If everything is good during the next couple of days I will enable it for the whole organization soon.
